"""empty message

Revision ID: d0f26dcb0640
Revises: 61a83bbf1a53
Create Date: 2020-07-22 11:08:36.247726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f26dcb0640'
down_revision = '61a83bbf1a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'section_id')
    # ### end Alembic commands ###
